name: upload-release-assets

on:
  push:
    tags:
      - '*'  # 任何标签推送会触发工作流

permissions:
  contents: write  # 确保有权限上传文件

jobs:
  upload_assets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and create JAR in core module
        run: ./gradlew :core:aamakeJar

      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/BlakQi/LitePal-DB/releases/latest/assets?name=gzandea-db-1.0.6.jar
          asset_path: core/build/libs/gzandea-db.jar
          asset_name: gzandea-db-1.0.6.jar
          asset_content_type: application/java-archive
