name: Build and Upload JAR

on:
  push:
    tags:
      - '*'  # 当任何 tag 被推送时触发

jobs:
  build-and-upload-jar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build JAR in core module
        run: ./gradlew :core:build

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}  # 使用推送的 tag 作为 release 的 tag 名
          release_name: Release ${{ github.ref_name }}  # Release 名字
          draft: false
          prerelease: false

      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: core/build/libs/gzandea-db.jar  # 确保路径正确
          asset_name: gzandea-db-${{ github.ref_name }}.jar  # 使用 tag 生成文件名
          asset_content_type: application/java-archive
