name: release

on:
  push:
    tags:
      - '*'  # 任何标签的推送都会触发这个工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and create JAR in core module
        run: ./gradlew :core:aamakeJar

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: gzandea-db-jar
          path: core/build/libs/gzandea-db.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Create a release based on the tag that triggered the workflow
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}  # 自动使用触发的标签名
          release_name: ${{ github.ref }}  # 自动使用触发的标签名作为 Release 名称
          draft: false
          prerelease: false

      # Upload the JAR to the release
      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: core/build/libs/gzandea-db.jar
          asset_name: gzandea-db-${{ github.ref }}.jar  # 使用标签作为文件名的一部分
          asset_content_type: application/java-archive
