name: release

on:
  push:
    tags:
      - '*'  # 任何标签的推送都会触发这个工作流

permissions:
  contents: write  # 授权写入权限

jobs:
  upload_assets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and create JAR in core module
        run: ./gradlew :core:aamakeJar

      - name: Get release by tag
        id: get_release
        uses: actions/github-script@v6
        with:
          script: |
            const tag = '${{ github.ref }}'.replace('refs/tags/', '');
            const releases = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const release = releases.data.find(r => r.tag_name === tag);
            if (!release) {
              throw new Error(`Release with tag ${tag} not found`);
            }
            return release.upload_url;

      # 上传 JAR 文件到现有的 Release Assets
      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: core/build/libs/gzandea-db.jar
          asset_name: gzandea-db-${{ github.ref }}.jar
          asset_content_type: application/java-archive
