name: Upload Release Assets

on:
  push:
    tags:
      - '*'  # 任何标签推送时触发

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build JAR in core module
        run: ./gradlew :core:build

      - name: Get Release ID if exists
        id: get_release_id
        uses: actions/github-script@v6
        with:
          script: |
            const tagName = context.ref.replace('refs/tags/', '');
            const releases = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const existingRelease = releases.data.find(release => release.tag_name === tagName);
            return existingRelease ? existingRelease.id : null;

      - name: Delete Existing Release
        if: steps.get_release_id.outputs.result != null
        uses: actions/github-script@v6
        with:
          script: |
            const releaseId = ${{ steps.get_release_id.outputs.result }};
            await github.repos.deleteRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: releaseId,
            });

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}  # 使用推送的标签创建 Release
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: core/build/libs/gzandea-db.jar  # 确保路径正确
          asset_name: gzandea-db-${{ github.ref_name }}.jar  # 使用当前 tag 作为文件名的一部分
          asset_content_type: application/java-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
