name: Upload Release Assets

on:
  push:
    tags:
      - '*'  # 任何标签推送时触发

jobs:
  upload_assets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build JAR in core module
        run: ./gradlew :core:build

      - name: Get the tag name
        id: get_tag_name
        run: echo "TAG_NAME=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV

      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }} # 这里不需要直接获取 Release 的 upload_url
          asset_path: core/build/libs/gzandea-db.jar  # 确保此路径正确
          asset_name: gzandea-db.jar  # 使用固定的文件名
          asset_content_type: application/java-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
